# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'RetoLiverpool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RetoLiverpool
  pod 'AlamofireSwiftyJSON'
  pod 'ObjectMapper'

  target 'RetoLiverpoolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RetoLiverpoolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
